name: NAAGA BACKEND PULL REQUEST CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'          # .md 확장자 파일들
      - '*.txt'         # .txt 확장자 파일들
      - '.gitignore'    # .gitignore 파일
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'          # .md 확장자 파일들
      - '*.txt'         # .txt 확장자 파일들
      - '.gitignore'    # .gitignore 파일
      
jobs:
  build_test:
    name: backend check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true  # 모든 서브모듈도 체크아웃
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
